@startuml
title Strategy Pattern - Before

class Order {
    - id : UUID
    - price : double
    - isClosed : boolean
    - customer : Customer
    - passengers : List<Passenger>
}

class FlightOrder {
    - flights : List<ScheduledFlight>
    + noFlyList : List<String> {static}
    + processOrderWithCreditCardDetail(number : String, expirationDate : Date, cvv : String) : boolean
    + processOrderWithCreditCard(card : CreditCard) : boolean
    + processOrderWithPayPal(email : String, password : String) : boolean
    + payWithCreditCard(card : CreditCard, amount : double) : boolean
    + payWithPayPal(email : String, password : String, amount : double) : boolean
}

class ScheduledFlight {
    - passengers : List<Passenger>
    - departureTime : Date
    - currentPrice : double
    + getCurrentPrice() : double
    + setCurrentPrice(currentPrice : double)
}

class CreditCard {
    - amount : double
    - number : String
    - date : Date
    - cvv : String
    - valid : boolean
    + isValid() : boolean
    + getAmount() : double
    + setAmount(amount : double)
}

class Paypal {
    + DATA_BASE : Map<String, String> {static}
}

FlightOrder --|> Order
FlightOrder --> "*" ScheduledFlight : flights
FlightOrder ..> CreditCard : card flow
FlightOrder ..> Paypal : paypal flow

@enduml
